### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by AfrifaEben7** [MedicineToken/Medical-SAM2#86]
I have rxt a2000 with Cuda 12.1. 
I tried to uninstall and install Anaconda, Nvidia drivers and Cudatoolkit. Still, the error is the same
Is there something that I am missing?

Running the 3D example BTCV.

WSL 2, ubuntu 20.04

**Comment by congmingyige** [comment]
Same problem. How to handle it?

```
python train_3d.py -net sam2 -exp_name BTCV_MedSAM2 -sam_ckpt ./checkpoints/sam2_hiera_small.pt -sam_config sam2_hiera_s -image_size 1024 -val_freq 1 -prompt bbox -prompt_freq 2 -dataset btcv -data_path ./data/btcv
/mnt/e/segment/Medical-SAM2/func_3d/function.py:41: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
INFO:root:Namespace(net='sam2', encoder='vit_b', exp_name='BTCV_MedSAM2', vis=False, train_vis=False, prompt='bbox', prompt_freq=2, pretrain=None, val_freq=1, gpu=True, gpu_device=0, image_size=1024, out_size=1024, distributed='none', dataset='btcv', sam_ckpt='./checkpoints/sam2_hiera_small.pt', sam_config='sam2_hiera_s', video_length=2, b=1, lr=0.0001, weights=0, multimask_output=1, memory_bank_size=16, data_path='./data/btcv', path_helper={'prefix': 'logs/BTCV_MedSAM2_2025_03_13_22_06_25', 'ckpt_path': 'logs/BTCV_MedSAM2_2025_03_13_22_06_25/Model', 'log_path': 'logs/BTCV_MedSAM2_2025_03_13_22_06_25/Log', 'sample_path': 'logs/BTCV_MedSAM2_2025_03_13_22_06_25/Samples'})
Namespace(net='sam2', encoder='vit_b', exp_name='BTCV_MedSAM2', vis=False, train_vis=False, prompt='bbox', prompt_freq=2, pretrain=None, val_freq=1, gpu=True, gpu_device=0, image_size=1024, out_size=1024, distributed='none', dataset='btcv', sam_ckpt='./checkpoints/sam2_hiera_small.pt', sam_config='sam2_hiera_s', video_length=2, b=1, lr=0.0001, weights=0, multimask_output=1, memory_bank_size=16, data_path='./data/btcv', path_helper={'prefix': 'logs/BTCV_MedSAM2_2025_03_13_22_06_25', 'ckpt_path': 'logs/BTCV_MedSAM2_2025_03_13_22_06_25/Model', 'log_path': 'logs/BTCV_MedSAM2_2025_03_13_22_06_25/Log', 'sample_path': 'logs/BTCV_MedSAM2_2025_03_13_22_06_25/Samples'})
Epoch 0:   0%|                                                                                  | 0/24 [00:39<?, ?img/s]
Traceback (most recent call last):
  File "/mnt/e/segment/Medical-SAM2/train_3d.py", line 118, in <module>
    main()
  File "/mnt/e/segment/Medical-SAM2/train_3d.py", line 101, in main
    loss, prompt_loss, non_prompt_loss = function.train_sam(args, net, optimizer1, optimizer2, nice_train_loader, epoch)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/segment/Medical-SAM2/func_3d/function.py", line 114, in train_sam
    _, _, _ = net.train_add_new_bbox(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/segment/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 439, in train_add_new_bbox
    out_frame_idx, out_obj_ids, out_mask_logits = self.train_add_new_points(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/segment/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 523, in train_add_new_points
    current_out, _ = self._run_single_frame_inference(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/segment/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 1351, in _run_single_frame_inference
    pred_masks_gpu = fill_holes_in_mask_scores(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/segment/Medical-SAM2/sam2_train/utils/misc.py", line 255, in fill_holes_in_mask_scores
    is_hole = (labels > 0) & (areas <= max_area)
               ^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
···

**Comment by xueyunfeng123** [comment]
Same issue；
A6000、cuda 12.4；
```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by xinyueliii** [comment]
同样的问题，有人解决了吗

**Comment by xueyunfeng123** [comment]
> 同样的问题，有人解决了吗

还没哎

**Comment by xinyueliii** [comment]
> 同样的问题，有人解决了吗

我这边解决了这个问题，可以参考https://github.com/SuperMedIntel/Medical-SAM2/issues/53这个issue，我这边先出现GLIBC_2.32这个问题，后面又出现cuda kernal的问题，总之应该就是版本问题，比较好的解决方案是用docker或者issue53中下面这个方法：（前提是保证pytorch 2.4, ubuntu 22.04, cuda 12.1及以上的版本）
I found one solution: go to the original Meta SAM2 repo, rebuild the SAM2, and replace the medsam2/sam_train/_C.so with the new built sam2/_C.so with.
How to rebuild sam2 can be found here,
https://github.com/facebookresearch/sam2/issues/53?ref=blog.roboflow.com?ref=blog.roboflow.com

**Comment by congmingyige** [comment]
> > 同样的问题，有人解决了吗
> 
> 我这边解决了这个问题，可以参考[https://github.com/SuperMedIntel/Medical-SAM2/issues/53这个issue，我这边先出现GLIBC_2.32这个问题，后面又出现cuda](https://github.com/SuperMedIntel/Medical-SAM2/issues/53%E8%BF%99%E4%B8%AAissue%EF%BC%8C%E6%88%91%E8%BF%99%E8%BE%B9%E5%85%88%E5%87%BA%E7%8E%B0GLIBC_2.32%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%EF%BC%8C%E5%90%8E%E9%9D%A2%E5%8F%88%E5%87%BA%E7%8E%B0cuda) kernal的问题，总之应该就是版本问题，比较好的解决方案是用docker或者issue53中下面这个方法：（前提是保证pytorch 2.4, ubuntu 22.04, cuda 12.1及以上的版本） I found one solution: go to the original Meta SAM2 repo, rebuild the SAM2, and replace the medsam2/sam_train/_C.so with the new built sam2/_C.so with. How to rebuild sam2 can be found here, https://github.com/facebookresearch/sam2/issues/53?ref=blog.roboflow.com?ref=blog.roboflow.com

I solve the problem by using this way.

My environment: ubuntu20.04, torch 2.5.1, cuda12.1, windows wsl.

Operation:
1. SAM repository: python setup.py build_ext --inplace. “_C.so" is updated.
2. copy “{SAM repository}\sam2\_C.so” to “{Medical-SAM2 repository}\sam2_train”

**Comment by AfrifaEben7** [comment]
I tried this and it is working now. Thanks a lot. The issue I am facing now is ; 

adapted image to btcv so I could use the datalaoder here.

3D image (stack) --> 369x369 - per frame

running on HPC;

![Image](https://github.com/user-attachments/assets/203d67be-9c32-40e9-8c9b-944a1f03e2af)

Any idea as to how to go about it would be great.

**Comment by AfrifaEben7** [comment]
> I tried this and it is working now. Thanks a lot. The issue I am facing now is ;
> 
> adapted image to btcv so I could use the datalaoder here.
> 
> 3D image (stack) --> 369x369 - per frame
> 
> running on HPC;
> 
> ![Image](https://github.com/user-attachments/assets/203d67be-9c32-40e9-8c9b-944a1f03e2af)
> 
> Any idea as to how to go about it would be great.

Fixed by reducing the dimensions of the image
